'use server';

import * as Sentry from '@sentry/nextjs';
import { revalidatePath } from 'next/cache';
import { createServerClient, createAdminClient } from '@/lib/supabase/server';
import { sendInviteEmail, sendNewLeadEmail } from '@/lib/email';
import { TRIAL_DAYS } from '@/lib/subscription/constants';
import { leadFormSchema, normalizeWhatsapp } from './schemas';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

// ---------------------------------------------------------------------------
// requireSuperadmin (local copy so we don't import from admin/actions)
// ---------------------------------------------------------------------------

async function requireSuperadmin() {
  const supabase = await createServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) throw new Error('UNAUTHORIZED');
  // Use admin client for role lookup to bypass RLS. The user.id comes from
  // the validated session above; this is safe.
  const admin = createAdminClient();
  const { data: row } = await admin
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single();
  if (row?.role !== 'superadmin') throw new Error('FORBIDDEN');
  return { user };
}

// ---------------------------------------------------------------------------
// createLead — callable by anonymous (public landing)
// ---------------------------------------------------------------------------

type CreateLeadResult = { ok: true } | { error: 'validation'; message: string } | { error: 'server_error' };

export async function createLead(formData: FormData): Promise<CreateLeadResult> {
  const raw = {
    email: formData.get('email'),
    name: formData.get('name'),
    whatsapp: formData.get('whatsapp'),
    plan: formData.get('plan'),
  };

  const parsed = leadFormSchema.safeParse(raw);
  if (!parsed.success) {
    return { error: 'validation', message: parsed.error.issues[0].message };
  }

  const { email, name, plan } = parsed.data;
  const whatsapp = normalizeWhatsapp(parsed.data.whatsapp) ?? parsed.data.whatsapp;

  const admin = createAdminClient();

  const { data: inserted, error: insertError } = await admin
    .from('leads')
    .insert({ email: email.toLowerCase(), name, whatsapp, plan })
    .select()
    .single();

  if (insertError || !inserted) {
    console.error('[createLead] INSERT error:', insertError?.message);
    Sentry.captureException(insertError ?? new Error('lead insert returned no data'), {
      tags: { feature: 'lead-capture' },
      extra: { plan },
    });
    return { error: 'server_error' };
  }

  // Mail failure must NOT block the success response
  try {
    await sendNewLeadEmail({ lead: inserted });
  } catch (e) {
    console.error('[createLead] sendNewLeadEmail failed:', e);
    Sentry.captureException(e, {
      tags: { feature: 'lead-capture' },
      extra: { leadId: inserted.id, plan },
    });
  }

  return { ok: true };
}

// ---------------------------------------------------------------------------
// approveLead — superadmin only
// ---------------------------------------------------------------------------

type ApproveLeadResult =
  | { ok: true; mail_sent: boolean; mail_error?: string }
  | { error: 'invalid_state' | 'already_whitelisted' | 'forbidden'; message?: string };

export async function approveLead({ id }: { id: string }): Promise<ApproveLeadResult> {
  let superadminUser: { id: string };
  try {
    const { user } = await requireSuperadmin();
    superadminUser = user;
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'FORBIDDEN';
    return { error: 'forbidden', message: msg };
  }

  const admin = createAdminClient();

  // 1. Fetch lead — must exist and be status='new'
  const { data: lead } = await admin
    .from('leads')
    .select('*')
    .eq('id', id)
    .eq('status', 'new')
    .single();

  if (!lead) {
    return { error: 'invalid_state', message: 'Lead no encontrado o ya procesado.' };
  }

  // 2. Check duplicate in whitelist
  const { data: existing } = await admin
    .from('whitelist')
    .select('id')
    .eq('email', lead.email.toLowerCase())
    .maybeSingle();

  if (existing) {
    return { error: 'already_whitelisted', message: 'Este mail ya estaba invitado.' };
  }

  // 3. INSERT whitelist row (invite_token generated by DB default)
  const trialEndsAt = new Date(Date.now() + TRIAL_DAYS * 24 * 60 * 60 * 1000).toISOString();

  const { data: whitelistRow, error: insertError } = await admin
    .from('whitelist')
    .insert({
      email: lead.email.toLowerCase(),
      grant_role: 'owner',
      plan: lead.plan,
      trial_ends_at: trialEndsAt,
    })
    .select('id, email, invite_token')
    .single();

  if (insertError || !whitelistRow) {
    return { error: 'invalid_state', message: insertError?.message ?? 'No se pudo crear whitelist row.' };
  }

  // 4. UPDATE lead status
  await admin
    .from('leads')
    .update({
      status: 'approved',
      approved_at: new Date().toISOString(),
      approved_by: superadminUser.id,
    })
    .eq('id', id);

  revalidatePath('/admin', 'layout');

  // 5. Send invite email
  if (!whitelistRow.invite_token) {
    return { ok: true, mail_sent: false, mail_error: 'No se generó invite_token.' };
  }

  const inviteUrl = `${APP_URL}/signup?token=${whitelistRow.invite_token}`;

  try {
    await sendInviteEmail({ to: whitelistRow.email, inviteUrl });
    return { ok: true, mail_sent: true };
  } catch (e) {
    const mailError = e instanceof Error ? e.message : 'Error desconocido';
    return { ok: true, mail_sent: false, mail_error: mailError };
  }
}

// ---------------------------------------------------------------------------
// deleteLead — superadmin only
// ---------------------------------------------------------------------------

type DeleteLeadResult = { ok: true } | { error: 'forbidden' | 'unknown'; message?: string };

export async function deleteLead({ id }: { id: string }): Promise<DeleteLeadResult> {
  try {
    await requireSuperadmin();
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'FORBIDDEN';
    return { error: 'forbidden', message: msg };
  }

  const admin = createAdminClient();
  const { error } = await admin.from('leads').delete().eq('id', id);

  if (error) {
    return { error: 'unknown', message: error.message };
  }

  revalidatePath('/admin', 'layout');
  return { ok: true };
}
